Try to fix ppc64 compilation errors in sip-sec-ntlm.c
mricon reported the following compilation error on ppc64:

sip-sec-ntlm.c: In function 'sip_sec_init_sec_context__ntlm':
sip-sec-ntlm.c:507: error: array subscript is above array bounds

I'm guessing the compiler barfs when asked to convert a signed 64-bit integer
to an unsigned 16-bit integer. But then why does it throw such a confusing
error message? If this theory is correct then the simple casting changes in
commit 9ee6663a9d3f3f7ef01a7d7d207236665f9aecba didn't work at all.

I replaced the int with guint16 to remove the conversion completely. But I
don't have access to a ppc64 system to verify the change.